### ISSUE TITLE
NMA Message not working

### ISSUE THREAD

**Issue by p00chie** [caronc/nzbget-notify#1]
I had to change the notify my android url:
NMA_URL = 'https://www.notifymyandroid.com/publicapi/notify/publicapi/notify'
to
NMA_URL = 'https://www.notifymyandroid.com/publicapi/notify'

In the logs i get

on Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] get(config) ONQUEUE="yes"
Mon Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] get(config) SERVERS="nma://apikey"
Mon Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] get(config) INCLUDEIMAGE="yes"
Mon Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] Server parsed to: {'host': 'apikey', 'user': None, 'query': None, 'url': 'nma://apikey', 'path': None, 'fullpath': None, 'password': None, 'port': None, 'schema': 'nma'}
Mon Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] NMA POST URL: https://www.notifymyandroid.com/publicapi/notify
Mon Jun 15 18:06:42 2015	INFO	Notify: [DEBUG] NMA Payload: {'priority': 0, 'application': 'NZBGet-Notify', 'apikey': 'apikey', 'event': 'New File Queued for Download', 'description': 'Message'}

But i do not receive any message on notify my android :(

**Comment by caronc** [comment]
Try fetching from the master branch; it should resolve your issue. I'll package it into a version when I address a few other small things I've been working on offline.

p.s. Thanks for additionally looking into the code and providing me the url link I had wrong!  That was indeed part of the solution!

**Comment by p00chie** [comment]
Thank you very much.
Problem solved!
